### ISSUE TITLE
panic: net/http: request canceled (Client.Timeout or context cancellation while reading body)

### ISSUE THREAD

**Issue by QinJun-1998** [wangluozhe/requests-go#17]
大佬您好，我的情景是用了多线程以及ip代理，然后会跑着跑着报如下错然后程序终止（有做了异常捕获但是程序还是是直接被终止掉的）

panic: net/http: request canceled (Client.Timeout or context cancellation while reading body)

goroutine 60 [running, locked to thread]:
github.com/wangluozhe/requests.(*Session).buildResponse(0xc003ed5860, 0xc00206cf30, 0xc002f63080, 0xc0018d4540)
	D:/Go/github.com/wangluozhe/requests/sessions.go:461 +0x4e5
github.com/wangluozhe/requests.(*Session).Send(0xc003ed5860, 0xc002f63080, 0xc0018d4540)
	D:/Go/github.com/wangluozhe/requests/sessions.go:449 +0xfdb
github.com/wangluozhe/requests.(*Session).Request(0xc004338de0?, {0xc00496b3b0?, 0xc00496b3b0?}, {0xc004d3bbc0, 0x5a}, 0x5a?)
	D:/Go/github.com/wangluozhe/requests/sessions.go:247 +0x170
main.request(0x0?)
	D:/Go/github.com/wangluozhe/requests/libs_dist/export.go:50 +0x12d

**Comment by wangluozhe** [comment]
此问题加群后获取新版dll测试看看

**Comment by wangluozhe** [comment]
新版本应该修复了此问题了，你再试试看有没有这个报错
