### ISSUE TITLE
OSError: dlopen

### ISSUE THREAD

**Issue by RoryXiang** [wangluozhe/requests-go#19]
Traceback (most recent call last):
  File "/Users/Desktop/requests-go/example/custom_tls.py", line 1, in <module>
    import requests_go as requests
  File "/Users/.virtualenvs/rory/lib/python3.7/site-packages/requests_go-0.4-py3.7.egg/requests_go/__init__.py", line 151, in <module>
    from .api import delete, get, head, options, patch, post, put, request
  File "/Users/.virtualenvs/rory/lib/python3.7/site-packages/requests_go-0.4-py3.7.egg/requests_go/api.py", line 11, in <module>
    from .sessions import Session
  File "/Users/.virtualenvs/rory/lib/python3.7/site-packages/requests_go-0.4-py3.7.egg/requests_go/sessions.py", line 11, in <module>
    from .adapters import TLSAdapter
  File "/Users/.virtualenvs/rory/lib/python3.7/site-packages/requests_go-0.4-py3.7.egg/requests_go/adapters.py", line 30, in <module>
    from .tls_client.exceptions import TLSClientExeption
  File "/Users/.virtualenvs/rory/lib/python3.7/site-packages/requests_go-0.4-py3.7.egg/requests_go/tls_client/__init__.py", line 1, in <module>
    from .request import Session
  File "/Users/.virtualenvs/rory/lib/python3.7/site-packages/requests_go-0.4-py3.7.egg/requests_go/tls_client/request.py", line 4, in <module>
    from .client import request, freeMemory
  File "/Users/.virtualenvs/rory/lib/python3.7/site-packages/requests_go-0.4-py3.7.egg/requests_go/tls_client/client.py", line 19, in <module>
    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/requests-go{file_ext}')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/.virtualenvs/rory/lib/python3.7/site-packages/requests_go-0.4-py3.7.egg/requests_go/tls_client/dependencies/requests-go-x86.dylib, 0x0006): tried: '/Users/.virtualenvs/rory/lib/python3.7/site-packages/requests_go-0.4-py3.7.egg/requests_go/tls_client/dependencies/requests-go-x86.dylib' (), '/System/Volumes/Preboot/Cryptexes/OS/Users/.virtualenvs/rory/lib/python3.7/site-packages/requests_go-0.4-py3.7.egg/requests_go/tls_client/dependencies/requests-go-x86.dylib' (no such file), '/Users/.virtualenvs/rory/lib/python3.7/site-packages/requests_go-0.4-py3.7.egg/requests_go/tls_client/dependencies/requests-go-x86.dylib' ()

**Comment by wangluozhe** [comment]
新版本已修复
