### ISSUE TITLE
some quesition about "requests.exceptions.ConnectionError: [Errno requests_go error:] {"err": "request->response"

### ISSUE THREAD

**Issue by Moss-001** [wangluozhe/requests-go#36]
```
`import requests_go

config = {
    "donate": "Please consider donating to keep this API running. Visit https://tls.peet.ws",
    "ip": "",
    "http_version": "h2",
    "method": "GET",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "tls": {
        "ciphers": [
            "TLS_GREASE (0x1A1A)",
            "TLS_AES_128_GCM_SHA256",
            "TLS_AES_256_GCM_SHA384",
            "TLS_CHACHA20_POLY1305_SHA256",
            "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
            "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
            "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
            "TLS_RSA_WITH_AES_128_GCM_SHA256",
            "TLS_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_RSA_WITH_AES_128_CBC_SHA",
            "TLS_RSA_WITH_AES_256_CBC_SHA"
        ],
        "extensions": [
            {
                "name": "TLS_GREASE (0xcaca)"
            },
            {
                "name": "supported_versions (43)",
                "versions": [
                    "TLS_GREASE (0xeaea)",
                    "TLS 1.3",
                    "TLS 1.2"
                ]
            },
            {
                "name": "key_share (51)",
                "shared_keys": [
                    {
                        "TLS_GREASE (0xfafa)": "00"
                    },
                    {
                        "X25519Kyber768 (25497)": "e715f07ca0d93508ae751bd01471b73f0bbd9fc19cd3564d87201fef7704ff148238a8dcd4870379c85fe79b9a7a7e7f038611a37ce8b3a10189aa5d8a867ad24ac8ca0a4e122458a683c3f0047968b529dc088feb6bda46064e81486cf7004b58368522106bebaf795447dbf414bf4038e2e7c571a2172c27af09ac7d87690f17b8bab1832781311a499625edc65b1cd987468487d9a15b8fd99db1cb353813c1b61a1008fa158d21954c645c1bc4394974befe60622a20b31a88ba4143a156b90f77b95d62e711edb0608007a51bdc04535b92890a6c81db18f8f8c209ec66b88781a5e1a0820511cd576ef379b02b68cedae65d882120eba875d1808a781515c33836e28b748a3b1baf356a51b713cfa6ad78f59cf7c5ab40184398223a8c53790ba3b433d1a9e16953f2727c8e343af0b8150c0bb91c656f89d19c87623034f61d1049167e7b55a2eb1575ba9e4c9b98ca839147170e5f994f8c46c96fd1268ed7c2689ab8431a1b18967d25981bd82ccde02963f84c25c74757442ab2b5c954bb095acd47399da1cb3453063025a53e86a45d50bbf0db8592a88f93926a629668b2f15ad6f61a5aaa92676516ce384491ca56d75b03d661a07f3b4884604e11137d2b4c8f4d5475a9c75cf86424b0811b75a16a0a149f4ab6ae49e06fce6429b38c03c7b88a907c3e72070286a4480a57b5fbaca5ca209000d44ef46b4d6bdbbabe7732673807b38003398ccd6cd67d6089bcb1e6072d30c96f471b2380cf90a06f64bba4930a584ce865e88b0ac755cb8069756630aab6321c0e423d1cf04a0ae4550c107def08805a758376dc46f2651b674984c2c50f613403a114b889590afe3a7d89ebcc88f61b35600b33e078c8d787e90ab5de2a37daf74c4b1aa8af10102225a51a594ed821c774151e6775591c2a685cc35d321a10edf7c58a92a6e5a718ebfca62aa816dc677be6097b73a5aa52950d91da3913369883a1c8543a14b6912e9f95496e3a5eab0c39e5879492425d60774fb3c13050962769e526927bca9e34265e5a6f3745c67dd4c64eb2c681b8a1797216b4ac1ac8f18945955d88f1b9ba2bc5a6b2040ac052cf89c2518572de5a5ac3520097e674b3ba7221e629b55b2f4ed539970a1008840ca1301c10b725bf753816f9ce38cbb54504896db5cfd3c5c2aad98251dc32ba8c21ad17097ba7b1235897e793603f473a2f737780f4305101ba547c3740b9b3a01897073513ea338e11a4cff8e3833abb8a2759bb19777c9b410cfc5c028034be42d77ebe27533a769a6a63c50429ca48188dc6c7cd2f989b73ac6336dc2532eb10e9787bc81c6b42639a683ba9e9265eea1c39bf9c9f201568ef5641e4b41479987754b25a597c709d367d7b9240847273c4c6bbda564a006aca364180479c97cd12cd3ce6a7d06a7ee66c3900cd5665b776e2ec2406794002008b408c02e7b80e91a9525a851bbf2cc61d33061863c3773017538348743128fee44afe52806f11409a29648a450bb74b94a543b39d12451d907ccbc72fd090970b528b819951bd7966c7030ca55393b28a0679bb38f55b39060b19c6ec4cc9db36bb6ba9659ab8821225d89a63998487cb7cc9200742a49189ace13bb3c2a10fec20c50975b0d4759017c4104140dd739a1c87aaa2851b14dbc5552f7106e140ce7d0c80a09e1f25b80b6560cc6e6cb9dec50b9db11c08"
                    },
                    {
                        "X25519 (29)": "66da3f7049a9baa452518ab688ba7699552b069c87bde780ff741d0c8baef90d"
                    }
                ]
            },
            {
                "name": "compress_certificate (27)",
                "algorithms": [
                    "brotli (2)"
                ]
            },
            {
                "name": "extensionEncryptedClientHello (boringssl) (65037)",
                "data": "00000100015600209aa036c3e01c4219a17dd4ad8c866740708ab702a7618ac5a0ced197353d251f00d00d766a5d695bdc676bdb085b3f4ff2be8a021cc6fc023c6215a91185f2fc828fd500b0f645e731554955151b0d3f8efc37bb8e32528f716da2ac5c08de261a1be011b429d2b7c978e9acae8204d268136a8d5d274a3a2b92ccbc439a5a8249f8d1c8a9472231122a9f464bb9c2448bf399883e61e5fab2deac9044190e56bd36ec4f7585da88e8ae4db3cfd88decebbd159d82d66f3086019eb4893919b9c7ba1e999353ef71c46abefecba6ab80ac9f889e6aab35c3b204724245f16d1edb86963af6ccfba0d8755d6142da2c144f1c"
            },
            {
                "name": "status_request (5)",
                "status_request": {
                    "certificate_status_type": "OSCP (1)",
                    "responder_id_list_length": 0,
                    "request_extensions_length": 0
                }
            },
            {
                "name": "extended_master_secret (23)",
                "master_secret_data": "",
                "extended_master_secret_data": ""
            },
            {
                "name": "application_settings (17513)",
                "protocols": [
                    "h2"
                ]
            },
            {
                "name": "application_layer_protocol_negotiation (16)",
                "protocols": [
                    "h2",
                    "http/1.1"
                ]
            },
            {
                "name": "signed_certificate_timestamp (18)"
            },
            {
                "name": "server_name (0)",
                "server_name": "tls.peet.ws"
            },
            {
                "name": "extensionRenegotiationInfo (boringssl) (65281)",
                "data": "00"
            },
            {
                "name": "signature_algorithms (13)",
                "signature_algorithms": [
                    "ecdsa_secp256r1_sha256",
                    "rsa_pss_rsae_sha256",
                    "rsa_pkcs1_sha256",
                    "ecdsa_secp384r1_sha384",
                    "rsa_pss_rsae_sha384",
                    "rsa_pkcs1_sha384",
                    "rsa_pss_rsae_sha512",
                    "rsa_pkcs1_sha512"
                ]
            },
            {
                "name": "psk_key_exchange_modes (45)",
                "PSK_Key_Exchange_Mode": "PSK with (EC)DHE key establishment (psk_dhe_ke) (1)"
            },
            {
                "name": "supported_groups (10)",
                "supported_groups": [
                    "TLS_GREASE (0xfafa)",
                    "X25519Kyber768 (25497)",
                    "X25519 (29)",
                    "P-256 (23)",
                    "P-384 (24)"
                ]
            },
            {
                "name": "session_ticket (35)",
                "data": ""
            },
            {
                "name": "ec_point_formats (11)",
                "elliptic_curves_point_formats": [
                    "0x00"
                ]
            },
            {
                "name": "TLS_GREASE (0xaaaa)"
            }
        ],
        "tls_version_record": "771",
        "tls_version_negotiated": "772",
        "ja3": "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,43-51-27-65037-5-23-17513-16-18-0-65281-13-45-10-35-11,25497-29-23-24,0",
        "ja3_hash": "ddfad88bd837cfa4cd6b6d99f37955b5",
        "ja4": "t13d1516h2_8daaf6152771_b1ff8ab2d16f",
        "peetprint": "GREASE-772-771|2-1.1|GREASE-25497-29-23-24|1027-2052-1025-1283-2053-1281-2054-1537|1|2|GREASE-4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53|0-10-11-13-16-17513-18-23-27-35-43-45-5-51-65037-65281-GREASE-GREASE",
        "peetprint_hash": "b8ce945a4d9a7a9b5b6132e3658fe033",
        "client_random": "84abce5ae330702105a0b3f157fc0360ed58e0b4cbde39b5cb554d9882d47b1b",
        "session_id": "7c04c2f3b32a2ff0e04b54fb418734e87d6d4d0b0b7b4896a93fd17a385e9d5b"
    },
    "http2": {
        "akamai_fingerprint": "1:65536,2:0,4:6291456,6:262144|15663105|0|m,a,s,p",
        "akamai_fingerprint_hash": "90224459f8bf70b7d0a8797eb916dbc9",
        "sent_frames": [
            {
                "frame_type": "SETTINGS",
                "length": 24,
                "settings": [
                    "HEADER_TABLE_SIZE = 65536",
                    "ENABLE_PUSH = 0",
                    "INITIAL_WINDOW_SIZE = 6291456",
                    "MAX_HEADER_LIST_SIZE = 262144"
                ]
            },
            {
                "frame_type": "WINDOW_UPDATE",
                "length": 4,
                "increment": 15663105
            },
            {
                "frame_type": "HEADERS",
                "stream_id": 1,
                "length": 476,
                "headers": [
                    ":method: GET",
                    ":authority: tls.peet.ws",
                    ":scheme: https",
                    ":path: /api/all",
                    "sec-ch-ua: \\\"GoogleChrome\\\";v=\\\"129\\\", \\\"Not=A?Brand\\\";v=\\\"8\\\", \\\"Chromium\\\";v=\\\"129\\",
                    "sec-ch-ua-mobile: ?0", "sec-ch-ua-platform: \\\"Windows\\",
                    "upgrade-insecure-requests: 1",
                    "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
                    "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
                    "sec-fetch-site: none",
                    "sec-fetch-mode: navigate",
                    "sec-fetch-user: ?1",
                    "sec-fetch-dest: document",
                    "accept-encoding: gzip, deflate, br, zstd",
                    "accept-language: zh-CN,zh;q=0.9,zh-HK;q=0.8,en;q=0.7",
                    "priority: u=0, i"
                ],
                "flags": [
                    "EndStream (0x1)",
                    "EndHeaders (0x4)",
                    "Priority (0x20)"
                ],
                "priority": {
                    "weight": 256,
                    "depends_on": 0,
                    "exclusive": 1
                }
            }
        ]
    },
    "tcpip": {
        "ip": {

        },
        "tcp": {

        }
    }
}

tls_config = requests_go.tls_config.to_tls_config(config)
tls_config.ja3 = requests_go.tls_config.JA3Random(tls_config.ja3)
response = requests_go.get('https://tls.browserleaks.com/json', tls_config=tls_config)
print(response.text)
```

> Traceback (most recent call last):

```
  File "E:\pycharmproject\spider_demo\akamai\TLS\fake_tls_2.py", line 227, in <module>
    response = requests_go.get('https://tls.browserleaks.com/json', tls_config=tls_config)
  File "E:\Anaconda3\envs\feapder_base\lib\site-packages\requests_go\api.py", line 74, in get
    return request("get", url, params=params, **kwargs)
  File "E:\Anaconda3\envs\feapder_base\lib\site-packages\requests_go\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda3\envs\feapder_base\lib\site-packages\requests_go\sessions.py", line 230, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda3\envs\feapder_base\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda3\envs\feapder_base\lib\site-packages\requests_go\adapters.py", line 476, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: [Errno requests_go error:] {"err": "request->response, err := GetSession(requestParams.Id).Request(requestParams.Method, requestParams.Url, req) failed: Get "https://tls.browserleaks.com/json": unsupported Curve in KeyShareExtension: CurveID(0).To mimic it, fill the Data(key) field manually"}
```

how to solve requests.exceptions.ConnectionError please
大佬，救命

**Comment by wangluozhe** [comment]
新版本已修复
`import requests_go

config = {
    "donate": "Please consider donating to keep this API running. Visit https://tls.peet.ws",
    "ip": "",
    "http_version": "h2",
    "method": "GET",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "tls": {
        "ciphers": [
            "TLS_GREASE (0x1A1A)",
            "TLS_AES_128_GCM_SHA256",
            "TLS_AES_256_GCM_SHA384",
            "TLS_CHACHA20_POLY1305_SHA256",
            "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
            "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
            "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
            "TLS_RSA_WITH_AES_128_GCM_SHA256",
            "TLS_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_RSA_WITH_AES_128_CBC_SHA",
            "TLS_RSA_WITH_AES_256_CBC_SHA"
        ],
        "extensions": [
            {
                "name": "TLS_GREASE (0xcaca)"
            },
            {
                "name": "supported_versions (43)",
                "versions": [
                    "TLS_GREASE (0xeaea)",
                    "TLS 1.3",
                    "TLS 1.2"
                ]
            },
            {
                "name": "key_share (51)",
                "shared_keys": [
                    {
                        "TLS_GREASE (0xfafa)": "00"
                    },
                    {
                        "X25519Kyber768 (25497)": "e715f07ca0d93508ae751bd01471b73f0bbd9fc19cd3564d87201fef7704ff148238a8dcd4870379c85fe79b9a7a7e7f038611a37ce8b3a10189aa5d8a867ad24ac8ca0a4e122458a683c3f0047968b529dc088feb6bda46064e81486cf7004b58368522106bebaf795447dbf414bf4038e2e7c571a2172c27af09ac7d87690f17b8bab1832781311a499625edc65b1cd987468487d9a15b8fd99db1cb353813c1b61a1008fa158d21954c645c1bc4394974befe60622a20b31a88ba4143a156b90f77b95d62e711edb0608007a51bdc04535b92890a6c81db18f8f8c209ec66b88781a5e1a0820511cd576ef379b02b68cedae65d882120eba875d1808a781515c33836e28b748a3b1baf356a51b713cfa6ad78f59cf7c5ab40184398223a8c53790ba3b433d1a9e16953f2727c8e343af0b8150c0bb91c656f89d19c87623034f61d1049167e7b55a2eb1575ba9e4c9b98ca839147170e5f994f8c46c96fd1268ed7c2689ab8431a1b18967d25981bd82ccde02963f84c25c74757442ab2b5c954bb095acd47399da1cb3453063025a53e86a45d50bbf0db8592a88f93926a629668b2f15ad6f61a5aaa92676516ce384491ca56d75b03d661a07f3b4884604e11137d2b4c8f4d5475a9c75cf86424b0811b75a16a0a149f4ab6ae49e06fce6429b38c03c7b88a907c3e72070286a4480a57b5fbaca5ca209000d44ef46b4d6bdbbabe7732673807b38003398ccd6cd67d6089bcb1e6072d30c96f471b2380cf90a06f64bba4930a584ce865e88b0ac755cb8069756630aab6321c0e423d1cf04a0ae4550c107def08805a758376dc46f2651b674984c2c50f613403a114b889590afe3a7d89ebcc88f61b35600b33e078c8d787e90ab5de2a37daf74c4b1aa8af10102225a51a594ed821c774151e6775591c2a685cc35d321a10edf7c58a92a6e5a718ebfca62aa816dc677be6097b73a5aa52950d91da3913369883a1c8543a14b6912e9f95496e3a5eab0c39e5879492425d60774fb3c13050962769e526927bca9e34265e5a6f3745c67dd4c64eb2c681b8a1797216b4ac1ac8f18945955d88f1b9ba2bc5a6b2040ac052cf89c2518572de5a5ac3520097e674b3ba7221e629b55b2f4ed539970a1008840ca1301c10b725bf753816f9ce38cbb54504896db5cfd3c5c2aad98251dc32ba8c21ad17097ba7b1235897e793603f473a2f737780f4305101ba547c3740b9b3a01897073513ea338e11a4cff8e3833abb8a2759bb19777c9b410cfc5c028034be42d77ebe27533a769a6a63c50429ca48188dc6c7cd2f989b73ac6336dc2532eb10e9787bc81c6b42639a683ba9e9265eea1c39bf9c9f201568ef5641e4b41479987754b25a597c709d367d7b9240847273c4c6bbda564a006aca364180479c97cd12cd3ce6a7d06a7ee66c3900cd5665b776e2ec2406794002008b408c02e7b80e91a9525a851bbf2cc61d33061863c3773017538348743128fee44afe52806f11409a29648a450bb74b94a543b39d12451d907ccbc72fd090970b528b819951bd7966c7030ca55393b28a0679bb38f55b39060b19c6ec4cc9db36bb6ba9659ab8821225d89a63998487cb7cc9200742a49189ace13bb3c2a10fec20c50975b0d4759017c4104140dd739a1c87aaa2851b14dbc5552f7106e140ce7d0c80a09e1f25b80b6560cc6e6cb9dec50b9db11c08"
                    },
                    {
                        "X25519 (29)": "66da3f7049a9baa452518ab688ba7699552b069c87bde780ff741d0c8baef90d"
                    }
                ]
            },
            {
                "name": "compress_certificate (27)",
                "algorithms": [
                    "brotli (2)"
                ]
            },
            {
                "name": "extensionEncryptedClientHello (boringssl) (65037)",
                "data": "00000100015600209aa036c3e01c4219a17dd4ad8c866740708ab702a7618ac5a0ced197353d251f00d00d766a5d695bdc676bdb085b3f4ff2be8a021cc6fc023c6215a91185f2fc828fd500b0f645e731554955151b0d3f8efc37bb8e32528f716da2ac5c08de261a1be011b429d2b7c978e9acae8204d268136a8d5d274a3a2b92ccbc439a5a8249f8d1c8a9472231122a9f464bb9c2448bf399883e61e5fab2deac9044190e56bd36ec4f7585da88e8ae4db3cfd88decebbd159d82d66f3086019eb4893919b9c7ba1e999353ef71c46abefecba6ab80ac9f889e6aab35c3b204724245f16d1edb86963af6ccfba0d8755d6142da2c144f1c"
            },
            {
                "name": "status_request (5)",
                "status_request": {
                    "certificate_status_type": "OSCP (1)",
                    "responder_id_list_length": 0,
                    "request_extensions_length": 0
                }
            },
            {
                "name": "extended_master_secret (23)",
                "master_secret_data": "",
                "extended_master_secret_data": ""
            },
            {
                "name": "application_settings (17513)",
                "protocols": [
                    "h2"
                ]
            },
            {
                "name": "application_layer_protocol_negotiation (16)",
                "protocols": [
                    "h2",
                    "http/1.1"
                ]
            },
            {
                "name": "signed_certificate_timestamp (18)"
            },
            {
                "name": "server_name (0)",
                "server_name": "tls.peet.ws"
            },
            {
                "name": "extensionRenegotiationInfo (boringssl) (65281)",
                "data": "00"
            },
            {
                "name": "signature_algorithms (13)",
                "signature_algorithms": [
                    "ecdsa_secp256r1_sha256",
                    "rsa_pss_rsae_sha256",
                    "rsa_pkcs1_sha256",
                    "ecdsa_secp384r1_sha384",
                    "rsa_pss_rsae_sha384",
                    "rsa_pkcs1_sha384",
                    "rsa_pss_rsae_sha512",
                    "rsa_pkcs1_sha512"
                ]
            },
            {
                "name": "psk_key_exchange_modes (45)",
                "PSK_Key_Exchange_Mode": "PSK with (EC)DHE key establishment (psk_dhe_ke) (1)"
            },
            {
                "name": "supported_groups (10)",
                "supported_groups": [
                    "TLS_GREASE (0xfafa)",
                    "X25519Kyber768 (25497)",
                    "X25519 (29)",
                    "P-256 (23)",
                    "P-384 (24)"
                ]
            },
            {
                "name": "session_ticket (35)",
                "data": ""
            },
            {
                "name": "ec_point_formats (11)",
                "elliptic_curves_point_formats": [
                    "0x00"
                ]
            },
            {
                "name": "TLS_GREASE (0xaaaa)"
            }
        ],
        "tls_version_record": "771",
        "tls_version_negotiated": "772",
        "ja3": "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,43-51-27-65037-5-23-17513-16-18-0-65281-13-45-10-35-11,25497-29-23-24,0",
        "ja3_hash": "ddfad88bd837cfa4cd6b6d99f37955b5",
        "ja4": "t13d1516h2_8daaf6152771_b1ff8ab2d16f",
        "peetprint": "GREASE-772-771|2-1.1|GREASE-25497-29-23-24|1027-2052-1025-1283-2053-1281-2054-1537|1|2|GREASE-4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53|0-10-11-13-16-17513-18-23-27-35-43-45-5-51-65037-65281-GREASE-GREASE",
        "peetprint_hash": "b8ce945a4d9a7a9b5b6132e3658fe033",
        "client_random": "84abce5ae330702105a0b3f157fc0360ed58e0b4cbde39b5cb554d9882d47b1b",
        "session_id": "7c04c2f3b32a2ff0e04b54fb418734e87d6d4d0b0b7b4896a93fd17a385e9d5b"
    },
    "http2": {
        "akamai_fingerprint": "1:65536,2:0,4:6291456,6:262144|15663105|0|m,a,s,p",
        "akamai_fingerprint_hash": "90224459f8bf70b7d0a8797eb916dbc9",
        "sent_frames": [
            {
                "frame_type": "SETTINGS",
                "length": 24,
                "settings": [
                    "HEADER_TABLE_SIZE = 65536",
                    "ENABLE_PUSH = 0",
                    "INITIAL_WINDOW_SIZE = 6291456",
                    "MAX_HEADER_LIST_SIZE = 262144"
                ]
            },
            {
                "frame_type": "WINDOW_UPDATE",
                "length": 4,
                "increment": 15663105
            },
            {
                "frame_type": "HEADERS",
                "stream_id": 1,
                "length": 476,
                "headers": [
                    ":method: GET",
                    ":authority: tls.peet.ws",
                    ":scheme: https",
                    ":path: /api/all",
                    "sec-ch-ua: \\\"GoogleChrome\\\";v=\\\"129\\\", \\\"Not=A?Brand\\\";v=\\\"8\\\", \\\"Chromium\\\";v=\\\"129\\",
                    "sec-ch-ua-mobile: ?0", "sec-ch-ua-platform: \\\"Windows\\",
                    "upgrade-insecure-requests: 1",
                    "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
                    "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
                    "sec-fetch-site: none",
                    "sec-fetch-mode: navigate",
                    "sec-fetch-user: ?1",
                    "sec-fetch-dest: document",
                    "accept-encoding: gzip, deflate, br, zstd",
                    "accept-language: zh-CN,zh;q=0.9,zh-HK;q=0.8,en;q=0.7",
                    "priority: u=0, i"
                ],
                "flags": [
                    "EndStream (0x1)",
                    "EndHeaders (0x4)",
                    "Priority (0x20)"
                ],
                "priority": {
                    "weight": 256,
                    "depends_on": 0,
                    "exclusive": 1
                }
            }
        ]
    },
    "tcpip": {
        "ip": {

        },
        "tcp": {

        }
    }
}

tls_config = requests_go.tls_config.to_tls_config(config)
tls_config.random_ja3 = True
response = requests_go.get('https://tls.browserleaks.com/json', tls_config=tls_config)
print(response.text)`

返回结果：
{
  "user_agent": "python-requests/2.32.3",
  "ja3_hash": "84c2d132c404bd8150de211d7e33466b",
  "ja3_text": "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,10-65037-35-13-5-16-11-17513-23-18-43-51-0-45-27-65281,25497-29-23-24,0",
  "ja3n_hash": "4c9ce26028c11d7544da00d3f7e4f45c",
  "ja3n_text": "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-5-10-11-13-16-18-23-27-35-43-45-51-17513-65037-65281,25497-29-23-24,0",
  "ja4": "t13d1516h2_8daaf6152771_02713d6af862",
  "ja4_r": "t13d1516h2_002f,0035,009c,009d,1301,1302,1303,c013,c014,c02b,c02c,c02f,c030,cca8,cca9_0005,000a,000b,000d,0012,0017,001b,0023,002b,002d,0033,4469,fe0d,ff01_0403,0804,0401,0503,0805,0501,0806,0601",
  "ja4_o": "t13d1516h2_acb858a92679_7ada0b14a686",
  "ja4_ro": "t13d1516h2_1301,1302,1303,c02b,c02f,c02c,c030,cca9,cca8,c013,c014,009c,009d,002f,0035_000a,fe0d,0023,000d,0005,0010,000b,4469,0017,0012,002b,0033,0000,002d,001b,ff01_0403,0804,0401,0503,0805,0501,0806,0601",
  "akamai_hash": "52d84b11737d980aef856699f885ca86",
  "akamai_text": "1:65536;2:0;4:6291456;6:262144|15663105|0|m,a,s,p"
}
